# Generated by Django 4.2.5 on 2023-09-21 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('price', models.CharField(max_length=20)),
                ('item_views', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('dibs', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=10)),
                ('is_sold', models.BooleanField(default=False)),
                ('sale_place', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrot_app.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrot_app.user'),
        ),
        migrations.CreateModel(
            name='ChattingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrot_app.item')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrot_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('chatting_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrot_app.chattingroom')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrot_app.user')),
            ],
        ),
    ]
