# Generated by Django 4.2.5 on 2023-09-26 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, null=True)),
                ('region_certification', models.CharField(default='N', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='carrot_app.user')),
            ],
        ),
    ]
