# Generated by Django 4.2.5 on 2023-09-26 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrot_app', '0002_userprofile_alter_chatting_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200, null=True)),
                ('shopinfo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegionShopProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_price', models.IntegerField()),
                ('option', models.CharField(max_length=200)),
                ('region_shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrot_app.regionshop')),
            ],
        ),
        migrations.CreateModel(
            name='RegionShopImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrot_app.regionshop')),
            ],
        ),
    ]
