# Generated by Django 4.2.5 on 2023-10-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrot_app', '0002_alter_regionshopimages_shop_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionshop',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='regionshop',
            name='thumnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
