# Generated by Django 4.2.5 on 2023-10-01 09:26

import carrot_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrot_app', '0003_regionshop_neighborhood_regionshop_thumnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionshop',
            name='thumnail',
            field=models.ImageField(null=True, upload_to=carrot_app.models.image_upload_to),
        ),
    ]
