# Generated by Django 4.2.5 on 2023-10-04 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrot_app', '0002_chatroom_message_remove_chattingroom_item_id_and_more'),
        ('carrot_app', '0005_alter_regionshopimages_image'),
    ]

    operations = [
    ]
