# Generated by Django 4.2.5 on 2023-10-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrot_app', '0006_merge_20231004_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionshop',
            name='category',
            field=models.CharField(default='all', max_length=50),
        ),
        migrations.AlterField(
            model_name='regionshop',
            name='shopinfo',
            field=models.TextField(),
        ),
    ]
