# Generated by Django 4.2.5 on 2023-10-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrot_app', '0006_merge_20231004_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='region',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
