# Generated by Django 4.2.5 on 2023-10-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrot_app', '0006_merge_20231004_1610'),
        ('carrot_app', '0007_item_region'),
        ('carrot_app', '0009_alter_regionshop_category'),
    ]

    operations = [
    ]
