# Generated by Django 4.2.5 on 2023-10-04 09:01

import carrot_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrot_app', '0010_merge_20231004_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/item'),
        ),
        migrations.AlterField(
            model_name='regionshop',
            name='thumnail',
            field=models.ImageField(blank=True, null=True, upload_to=carrot_app.models.image_upload_to),
        ),
        migrations.AlterField(
            model_name='regionshopimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=carrot_app.models.image_upload),
        ),
    ]
