# Generated by Django 4.2.5 on 2023-10-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrot_app', '0011_alter_itemimage_item_image_alter_regionshop_thumnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionshopproductprice',
            name='product_price',
            field=models.CharField(max_length=20),
        ),
    ]
